Pipeline: Investigate 404s from the API during SITS
- Add timestamps and detailed messages to healthcheck failures so they
  can be correlated with other errors when they occur.

- We still didn't find any definitive causes of the 404s.

[Finishes #166748671](https://www.pivotaltracker.com/story/show/166748671)

Co-authored-by: Eric Promislow <eric.promislow@suse.com>
Co-authored-by: Renee Chu <rchu@pivotal.io>

diff --git a/jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb b/jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb
--- a/jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb
+++ b/jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb
@@ -22,7 +22,7 @@ set -e
 %>
 
 function log_failure {
-  echo "$(date --rfc-3339=seconds) :: Healthcheck failed consistently, restarting CC"
+  echo "$(date --rfc-3339=ns) :: Healthcheck failed consistently, restarting CC"
 }
 
 HOST=<%= p('cc.nginx.ip').empty? ? discover_external_ip : p('cc.nginx.ip') %>
@@ -32,24 +32,28 @@ URL="https://${HOST}:${PORT}/healthz"
 
 source /var/vcap/packages/capi_utils/monit_utils.sh
 
-echo 'Waiting for Cloud Controller to initially become healthy'
+echo $(date --rfc-3339=ns) 'Waiting for Cloud Controller to initially become healthy at'
 
 wait_for_server_to_become_healthy "${URL}" "<%= p("cc.api_post_start_healthcheck_timeout_in_seconds") %>"
 
-echo 'Initial check passed, will now restart CC over on repeated failures'
+echo $(date --rfc-3339=ns) 'Initial check passed, will now restart CC over on repeated failures'
 
 trap log_failure EXIT
 
 # if we fail to curl it 5 times in a row across 50 seconds, die so monit will restart us
 set -e
 while true; do
-  curl \
+  if ! curl \
     -sS \
     --max-time <%= p('cc.api_health_check_timeout_per_retry') %> \
     --retry 5 \
     --retry-delay 10 \
     -A "ccng_monit_http_healthcheck" \
     -k \
-    "${URL}" > /dev/null
+    "${URL}" > /dev/null ; then
+    status=$?
+    echo $(date --rfc-3339=ns) "ccng_monit_http_healthcheck failed to curl <${URL}>: exit code $status"
+    exit $status
+  fi
   sleep 10
 done
diff --git a/jobs/cloud_controller_ng/templates/cloud_controller_api_health_check.erb b/jobs/cloud_controller_ng/templates/cloud_controller_api_health_check.erb
--- a/jobs/cloud_controller_ng/templates/cloud_controller_api_health_check.erb
+++ b/jobs/cloud_controller_ng/templates/cloud_controller_api_health_check.erb
@@ -5,6 +5,7 @@
 PORT=<%= p("cc.public_tls.port") %>
 URL="https://localhost:${PORT}/healthz"
 
+echo $(date --rfc-3339=ns) "cloud_controller_ng_health_check: route-registrar about to curl $URL"
 curl \
   --max-time <%= p('cc.api_health_check_timeout_per_retry') %> \
   --retry-max-time <%= p('cc.api_health_check_total_timeout') %> \
@@ -12,4 +13,9 @@ curl \
   --retry-delay 1 \
   -k \
   "${URL}"
+status=$?
+if [[ $status > 0 ]] ; then
+  echo $(date --rfc-3339=ns) "Failed to hit ${URL}"
+  exit $status
+fi
 
