Remove dev/test gems from release package (#436)
Dependencies that are only needed for dev and test but are not used at CC runtime should be removed from the capi-release package.
Therefore modifiyng Gemfile in pre-package to remove group test and
development before packaging.

diff --git a/packages/cloud_controller_ng/pre_packaging b/packages/cloud_controller_ng/pre_packaging
--- a/packages/cloud_controller_ng/pre_packaging
+++ b/packages/cloud_controller_ng/pre_packaging
@@ -2,22 +2,34 @@ set -e -x
 
 cd ${BUILD_DIR}/cloud_controller_ng
 
+input_file="Gemfile"
+
+if [[ ! -f "$input_file" ]]; then
+  echo "Error: $input_file does not exist."
+  exit 1
+fi
+
+file_content=$(<"$input_file")
+modified_content=$(echo "$file_content" | sed '/^group :development do/,/^end/ d' | sed '/^group :test do/,/^end/ d')
+echo "$modified_content" > "$input_file"
+
 rm -rf ./vendor/cache/
 
-set +e
 for i in {1..3}; do
   bundle config --local specific_platform true
   bundle config --local path ./vendor/cache
   bundle config set cache_all true
+  set +e
   bundle package --all-platforms --no-install
   exit_code="$?"
+  set -e
 
   if [ "${exit_code}" == "0" ]; then
     break
   fi
   sleep 1
 done
-set -e
+
 if [ "${exit_code}" != "0" ]; then
   echo "ERROR: Failed to run 'bundle package' after 3 attempts"
   exit "${exit_code}"
